// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5vHsGbeGZpkwcnHnbaxiusnh4RJufqcM',
    appId: '1:986918938285:web:deed10a004f04288838824',
    messagingSenderId: '986918938285',
    projectId: 'mal-learn-2',
    authDomain: 'mal-learn-2.firebaseapp.com',
    storageBucket: 'mal-learn-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMXHmKCjbwhAF1rXv_iL319X24eoh4i_4',
    appId: '1:986918938285:android:f48a8c86b9060f69838824',
    messagingSenderId: '986918938285',
    projectId: 'mal-learn-2',
    storageBucket: 'mal-learn-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNlo3kw4ttK-bREeaaYt0_SyaE_ZIo1k4',
    appId: '1:986918938285:ios:67ceec7eb78f72d1838824',
    messagingSenderId: '986918938285',
    projectId: 'mal-learn-2',
    storageBucket: 'mal-learn-2.appspot.com',
    iosClientId: '986918938285-dibi6i74b69dfcm68r11s3fk5io5mi3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.malLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNlo3kw4ttK-bREeaaYt0_SyaE_ZIo1k4',
    appId: '1:986918938285:ios:67ceec7eb78f72d1838824',
    messagingSenderId: '986918938285',
    projectId: 'mal-learn-2',
    storageBucket: 'mal-learn-2.appspot.com',
    iosClientId: '986918938285-dibi6i74b69dfcm68r11s3fk5io5mi3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.malLearn',
  );
}
